steps:


- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      import pyautogui
      1920, 1080 = pyautogui.size()
      print('Hello world 2')
      pyautogui.moveTo(100, 150)
      pyautogui.click(100, 200)
      pyautogui.move(400, 0)
